# Site settings
title: "[DEV] Nibble"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  [DEV] Nibble's description
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
host: 0.0.0.0

# Build settings
markdown: kramdown
